### PR TITLE
Minor clean-up and PHP notice fix

### PR DESCRIPTION
**Pull request by markhowellsmead**

### CODE REVIEW

**Review by nasyrov — COMMENTED** [review]
LGTM

**Review by nasyrov — CHANGES_REQUESTED** [review]
Could you please remove the legacy constructor and tidy up the white spaces? As well, change &$this to simply $this.

Cheers

**Comment by markhowellsmead** [comment]
Why?

**Comment by nasyrov** [comment]
@markhowellsmead it's deprecated

**Comment by markhowellsmead** [comment]
That's outside the scope of this change request. Please contact the author of the repository for functional changes and code improvements.

**Comment by nasyrov** [comment]
@markhowellsmead I'll do it then and merge it.

**Comment by nasyrov** [comment]
Closing this, no further work has been done on contributor's side.

**Comment by markhowellsmead** [comment]
Thanks!

**Pull request closed without merging**
